language: node_js

services:
  - docker

node_js:
  - 12
  - 10 # minimal supported node version

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

# Retry install on fail to avoid failing a build on network/disk/external errors
install:
  - travis_retry npm install

script:
  - npm run test

<<<<<<< HEAD
=======
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run release

>>>>>>> dev
